const quotes = [
  {
    q: "Success is like reaching an important birthday and finding you're exactly the same.",
    a: "Audrey Hepburn",
    c: 83,
    h: "\u003Cblockquote\u003E&ldquo;Success is like reaching an important birthday and finding you&#039;re exactly the same.&rdquo; &mdash; \u003Cfooter\u003EAudrey Hepburn\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Genius is patience.",
    a: "Isaac Newton",
    c: 19,
    h: "\u003Cblockquote\u003E&ldquo;Genius is patience.&rdquo; &mdash; \u003Cfooter\u003EIsaac Newton\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "But better die than live mechanically a life that is a repetition of repetitions.",
    a: "D. H. Lawrence",
    c: 81,
    h: "\u003Cblockquote\u003E&ldquo;But better die than live mechanically a life that is a repetition of repetitions.&rdquo; &mdash; \u003Cfooter\u003ED. H. Lawrence\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "As mortals, we're ruled by conditions, not by ourselves.",
    a: "Bodhidharma",
    c: 56,
    h: "\u003Cblockquote\u003E&ldquo;As mortals, we&#039;re ruled by conditions, not by ourselves.&rdquo; &mdash; \u003Cfooter\u003EBodhidharma\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "It still holds true that man is most uniquely human when he turns obstacles into opportunities.",
    a: "Eric Hoffer",
    c: 95,
    h: "\u003Cblockquote\u003E&ldquo;It still holds true that man is most uniquely human when he turns obstacles into opportunities.&rdquo; &mdash; \u003Cfooter\u003EEric Hoffer\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "True wisdom comes to each of us when we realize how little we understand about life, ourselves, and the world around us.",
    a: "Socrates",
    c: 120,
    h: "\u003Cblockquote\u003E&ldquo;True wisdom comes to each of us when we realize how little we understand about life, ourselves, and the world around us.&rdquo; &mdash; \u003Cfooter\u003ESocrates\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Whether you think you can or think you can't – you are right.",
    a: "Henry Ford",
    c: 63,
    h: "\u003Cblockquote\u003E&ldquo;Whether you think you can or think you can&#039;t – you are right.&rdquo; &mdash; \u003Cfooter\u003EHenry Ford\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Why do you stay in prison when the door is so wide open?",
    a: "Rumi",
    c: 56,
    h: "\u003Cblockquote\u003E&ldquo;Why do you stay in prison when the door is so wide open?&rdquo; &mdash; \u003Cfooter\u003ERumi\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "To find yourself, think for yourself.",
    a: "Socrates",
    c: 37,
    h: "\u003Cblockquote\u003E&ldquo;To find yourself, think for yourself.&rdquo; &mdash; \u003Cfooter\u003ESocrates\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "If you think you can do a thing or think you can't do a thing, you're right.",
    a: "Henry Ford",
    c: 76,
    h: "\u003Cblockquote\u003E&ldquo;If you think you can do a thing or think you can&#039;t do a thing, you&#039;re right.&rdquo; &mdash; \u003Cfooter\u003EHenry Ford\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Success is about doing the right thing, not about doing everything right.",
    a: "Gary Keller",
    c: 73,
    h: "\u003Cblockquote\u003E&ldquo;Success is about doing the right thing, not about doing everything right.&rdquo; &mdash; \u003Cfooter\u003EGary Keller\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "To be in harmony with the wholeness of things is not to have anxiety over imperfections.",
    a: "Dogen",
    c: 88,
    h: "\u003Cblockquote\u003E&ldquo;To be in harmony with the wholeness of things is not to have anxiety over imperfections.&rdquo; &mdash; \u003Cfooter\u003EDogen\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Aim for the moon. If you miss, you may hit a star.",
    a: "W. Clement Stone",
    c: 50,
    h: "\u003Cblockquote\u003E&ldquo;Aim for the moon. If you miss, you may hit a star.&rdquo; &mdash; \u003Cfooter\u003EW. Clement Stone\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "With self-discipline, almost anything is possible.",
    a: "Theodore Roosevelt",
    c: 50,
    h: "\u003Cblockquote\u003E&ldquo;With self-discipline, almost anything is possible.&rdquo; &mdash; \u003Cfooter\u003ETheodore Roosevelt\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Life does not get better by chance, it gets better by change.",
    a: "Jim Rohn",
    c: 61,
    h: "\u003Cblockquote\u003E&ldquo;Life does not get better by chance, it gets better by change.&rdquo; &mdash; \u003Cfooter\u003EJim Rohn\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Through selfless service, you will always be fruitful and find the fulfillment of your desires.",
    a: "Bhagavad Gita",
    c: 95,
    h: "\u003Cblockquote\u003E&ldquo;Through selfless service, you will always be fruitful and find the fulfillment of your desires.&rdquo; &mdash; \u003Cfooter\u003EBhagavad Gita\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Shoot for the moon. Even if you miss, you'll land among the stars.",
    a: "Norman Vincent Peale",
    c: 66,
    h: "\u003Cblockquote\u003E&ldquo;Shoot for the moon. Even if you miss, you&#039;ll land among the stars.&rdquo; &mdash; \u003Cfooter\u003ENorman Vincent Peale\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Your heart is full of fertile seeds, waiting to sprout.",
    a: "Morihei Ueshiba",
    c: 55,
    h: "\u003Cblockquote\u003E&ldquo;Your heart is full of fertile seeds, waiting to sprout.&rdquo; &mdash; \u003Cfooter\u003EMorihei Ueshiba\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "The world is changed by your example, not by your opinion.",
    a: "Paulo Coelho",
    c: 58,
    h: "\u003Cblockquote\u003E&ldquo;The world is changed by your example, not by your opinion.&rdquo; &mdash; \u003Cfooter\u003EPaulo Coelho\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "The important thing is not to stop questioning. Curiosity has its own reason for existing.",
    a: "Albert Einstein",
    c: 90,
    h: "\u003Cblockquote\u003E&ldquo;The important thing is not to stop questioning. Curiosity has its own reason for existing.&rdquo; &mdash; \u003Cfooter\u003EAlbert Einstein\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Any fool can turn a blind eye but who knows what the ostrich sees in the sand.",
    a: "Samuel Beckett",
    c: 78,
    h: "\u003Cblockquote\u003E&ldquo;Any fool can turn a blind eye but who knows what the ostrich sees in the sand.&rdquo; &mdash; \u003Cfooter\u003ESamuel Beckett\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Do not be awe struck by other people and try to copy them. Nobody can be you as efficiently as you can.",
    a: "Norman Vincent Peale",
    c: 103,
    h: "\u003Cblockquote\u003E&ldquo;Do not be awe struck by other people and try to copy them. Nobody can be you as efficiently as you can.&rdquo; &mdash; \u003Cfooter\u003ENorman Vincent Peale\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Having an open mind is one of the most important qualities we can possess. Once our minds close, we stop evolving.",
    a: "Yanni",
    c: 114,
    h: "\u003Cblockquote\u003E&ldquo;Having an open mind is one of the most important qualities we can possess. Once our minds close, we stop evolving.&rdquo; &mdash; \u003Cfooter\u003EYanni\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Always show more kindness than seems necessary because the person receiving it needs it more than you will ever know.",
    a: "Colin Powell",
    c: 117,
    h: "\u003Cblockquote\u003E&ldquo;Always show more kindness than seems necessary because the person receiving it needs it more than you will ever know.&rdquo; &mdash; \u003Cfooter\u003EColin Powell\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Empty yourself of everything - let the mind become still.",
    a: "Lao Tzu",
    c: 57,
    h: "\u003Cblockquote\u003E&ldquo;Empty yourself of everything - let the mind become still.&rdquo; &mdash; \u003Cfooter\u003ELao Tzu\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Art is to console those who are broken by life.",
    a: "Vincent van Gogh",
    c: 47,
    h: "\u003Cblockquote\u003E&ldquo;Art is to console those who are broken by life.&rdquo; &mdash; \u003Cfooter\u003EVincent van Gogh\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Great things are not accomplished by those who yield to trends and fads and popular opinion.",
    a: "Jack Kerouac",
    c: 92,
    h: "\u003Cblockquote\u003E&ldquo;Great things are not accomplished by those who yield to trends and fads and popular opinion.&rdquo; &mdash; \u003Cfooter\u003EJack Kerouac\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Find the game where you can win, and then commit your life to playing it; and play to win.",
    a: "Robert Kiyosaki",
    c: 90,
    h: "\u003Cblockquote\u003E&ldquo;Find the game where you can win, and then commit your life to playing it; and play to win.&rdquo; &mdash; \u003Cfooter\u003ERobert Kiyosaki\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Forgive those who have hurt you.",
    a: "Les Brown",
    c: 32,
    h: "\u003Cblockquote\u003E&ldquo;Forgive those who have hurt you.&rdquo; &mdash; \u003Cfooter\u003ELes Brown\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "In the end, it's not the years in your life that count. It's the life in your years.",
    a: "Abraham Lincoln",
    c: 84,
    h: "\u003Cblockquote\u003E&ldquo;In the end, it&#039;s not the years in your life that count. It&#039;s the life in your years.&rdquo; &mdash; \u003Cfooter\u003EAbraham Lincoln\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "In the middle of chaos lies opportunity.",
    a: "Bruce Lee",
    c: 40,
    h: "\u003Cblockquote\u003E&ldquo;In the middle of chaos lies opportunity.&rdquo; &mdash; \u003Cfooter\u003EBruce Lee\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "A crisis is an opportunity riding the dangerous wind.",
    a: "Chinese Proverb",
    c: 53,
    h: "\u003Cblockquote\u003E&ldquo;A crisis is an opportunity riding the dangerous wind.&rdquo; &mdash; \u003Cfooter\u003EChinese Proverb\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Inspire yourself to be great. Being good isn't good enough.",
    a: "Gurbaksh Chahal",
    c: 59,
    h: "\u003Cblockquote\u003E&ldquo;Inspire yourself to be great. Being good isn&#039;t good enough.&rdquo; &mdash; \u003Cfooter\u003EGurbaksh Chahal\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "From the errors of others, a wise man corrects his own.",
    a: "Publilius Syrus",
    c: 55,
    h: "\u003Cblockquote\u003E&ldquo;From the errors of others, a wise man corrects his own.&rdquo; &mdash; \u003Cfooter\u003EPublilius Syrus\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Success is a consequence and must not be a goal.",
    a: "Gustave Flaubert",
    c: 48,
    h: "\u003Cblockquote\u003E&ldquo;Success is a consequence and must not be a goal.&rdquo; &mdash; \u003Cfooter\u003EGustave Flaubert\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.",
    a: "Epictetus",
    c: 102,
    h: "\u003Cblockquote\u003E&ldquo;Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.&rdquo; &mdash; \u003Cfooter\u003EEpictetus\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Every limit is a beginning as well as an ending.",
    a: "George Eliot",
    c: 48,
    h: "\u003Cblockquote\u003E&ldquo;Every limit is a beginning as well as an ending.&rdquo; &mdash; \u003Cfooter\u003EGeorge Eliot\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Great acts are made up of small deeds.",
    a: "Lao Tzu",
    c: 38,
    h: "\u003Cblockquote\u003E&ldquo;Great acts are made up of small deeds.&rdquo; &mdash; \u003Cfooter\u003ELao Tzu\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Do not take life too seriously. You will never get out of it alive.",
    a: "Elbert Hubbard",
    c: 67,
    h: "\u003Cblockquote\u003E&ldquo;Do not take life too seriously. You will never get out of it alive.&rdquo; &mdash; \u003Cfooter\u003EElbert Hubbard\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Before enlightenment; chop wood, carry water. After enlightenment; chop wood, carry water.",
    a: "Buddha",
    c: 90,
    h: "\u003Cblockquote\u003E&ldquo;Before enlightenment; chop wood, carry water. After enlightenment; chop wood, carry water.&rdquo; &mdash; \u003Cfooter\u003EBuddha\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "The face is the mirror of the mind, and eyes without speaking confess the secrets of the heart.",
    a: "St. Jerome",
    c: 95,
    h: "\u003Cblockquote\u003E&ldquo;The face is the mirror of the mind, and eyes without speaking confess the secrets of the heart.&rdquo; &mdash; \u003Cfooter\u003ESt. Jerome\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Where there's life, there's hope.",
    a: "Stephen Hawking",
    c: 33,
    h: "\u003Cblockquote\u003E&ldquo;Where there&#039;s life, there&#039;s hope.&rdquo; &mdash; \u003Cfooter\u003EStephen Hawking\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Surround yourself with people who take their work seriously, but not themselves, those who work hard and play hard.",
    a: "Colin Powell",
    c: 115,
    h: "\u003Cblockquote\u003E&ldquo;Surround yourself with people who take their work seriously, but not themselves, those who work hard and play hard.&rdquo; &mdash; \u003Cfooter\u003EColin Powell\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "It is not uncommon for people to spend their whole life waiting to start living.",
    a: "Eckhart Tolle",
    c: 80,
    h: "\u003Cblockquote\u003E&ldquo;It is not uncommon for people to spend their whole life waiting to start living.&rdquo; &mdash; \u003Cfooter\u003EEckhart Tolle\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Those who bring sunshine into the lives of others cannot keep it from themselves.",
    a: "James Matthew Barrie",
    c: 81,
    h: "\u003Cblockquote\u003E&ldquo;Those who bring sunshine into the lives of others cannot keep it from themselves.&rdquo; &mdash; \u003Cfooter\u003EJames Matthew Barrie\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "The mirror is a worthless invention. The only way to truly see yourself is in the reflection of someone elses. eyes.",
    a: "Voltaire",
    c: 116,
    h: "\u003Cblockquote\u003E&ldquo;The mirror is a worthless invention. The only way to truly see yourself is in the reflection of someone elses. eyes.&rdquo; &mdash; \u003Cfooter\u003EVoltaire\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "In the beginner's mind there are many possibilities, but in the expert's mind there are few.",
    a: "Shunryu Suzuki",
    c: 92,
    h: "\u003Cblockquote\u003E&ldquo;In the beginner&#039;s mind there are many possibilities, but in the expert&#039;s mind there are few.&rdquo; &mdash; \u003Cfooter\u003EShunryu Suzuki\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Your worth consists in what you are and not in what you have.",
    a: "Thomas Edison",
    c: 61,
    h: "\u003Cblockquote\u003E&ldquo;Your worth consists in what you are and not in what you have.&rdquo; &mdash; \u003Cfooter\u003EThomas Edison\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "What people need and what they want may be very different.",
    a: "Elbert Hubbard",
    c: 58,
    h: "\u003Cblockquote\u003E&ldquo;What people need and what they want may be very different.&rdquo; &mdash; \u003Cfooter\u003EElbert Hubbard\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "The whole of life, from the moment you are born to the moment you die, is a process of learning.",
    a: "Jiddu Krishnamurti",
    c: 96,
    h: "\u003Cblockquote\u003E&ldquo;The whole of life, from the moment you are born to the moment you die, is a process of learning.&rdquo; &mdash; \u003Cfooter\u003EJiddu Krishnamurti\u003C/footer\u003E\u003C/blockquote\u003E",
  },
];

export default quotes;
